### ISSUE TITLE
Error in 'mutate()' when testing VaQuERo.r

### ISSUE THREAD

**Issue by evantroendle** [fabou-uobaf/VaQuERo#3]
Hello,

I wish to attempt applying VaQuERo in my research collaboration, but I cannot successfully execute the script on the included example data. 

I will first describe how one may reproduce my installation and prep-work if you could please direct me as to what is incorrect.

I am running Ubuntu 20.04, and have R version 4.2.1.

I copied the present source code using:
git clone https://github.com/fabou-uobaf/VaQuERo.git

I have installed the following ubuntu dependencies:
sudo apt install libssl-dev libudunits2-dev gdal-bin libgdal-dev

and then executed the following R library installation commands: (pasted in an *.r script 'setup_VaQuERo.r' and ran via sudo Rscript setup_VaQuERo.r'

install.packages('tidyr')
install.packages('ggplot2')
install.packages('reshape2')
install.packages('dplyr')
install.packages('data.table')
install.packages('gamlss')
install.packages('ggmap')
install.packages('tmaptools')
install.packages('ggrepel')
install.packages('scales')
install.packages('betareg')
install.packages('ggspatial')
install.packages('sf')
install.packages('rnaturalearth')
install.packages('rnaturalearthdata')
install.packages('optparse')
install.packages('stringr')
install.packages('lubridate')

NB: lubridate was not mentioned under https://github.com/fabou-uobaf/VaQuERo#install

To attempt running the code, I first tried (within the VaQuERo directory):
Rscript scripts/VaQuERo.r > vaquero.log

However, I first received an error:
Error in fread(file = markermutationFile) :
  File 'resources/mutations_list.csv' does not exist or is non-readable. getwd()=='/home/evan/Documents/R/VaQuERo/VaQuERo'
and another similar error after attempting a fix (see below) regarding the mutations_special.csv file.:
Error in fread(file = specialmutationFile) :
  File 'resources/mutations_special.csv' does not exist or is non-readable. getwd()=='/home/evan/Documents/R/VaQuERo/VaQuERo'

my attempted remedy was:
cp resources/mutations_list_grouped_2022-06-20_Austria.csv resources/mutations_list.csv
cp resources/mutations_special_2022-07-04.csv resources/mutations_special.csv

This appears to have worked somewhat, but I get the following warnings and errors (console output pasted below), and I do not know how to proceed. 

Warning(s): BA.2 can bnot be detected since only 1 unique markers defined, but 3 needed
Warning(s): BA.4 can bnot be detected since only 2 unique markers defined, but 3 needed
Warning(s): BA.5 can bnot be detected since only 2 unique markers defined, but 3 needed
Error in `mutate()`:
! Problem while computing `sample_date_decimal =
  decimalDate(sample_date, n)`.
Caused by error in `if ((y%%4) == 0) ...`:
! the condition has length > 1
Backtrace:
     ▆
  1. ├─... %>% dplyr::select(-n)
  2. ├─dplyr::select(., -n)
  3. ├─dplyr::mutate(...)
  4. ├─dplyr:::mutate.data.frame(., sample_date_decimal = decimalDate(sample_date, n))
  5. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
  6. │   ├─base::withCallingHandlers(...)
  7. │   └─mask$eval_all_mutate(quo)
  8. ├─global decimalDate(sample_date, n)
  9. │ └─global leapYear(year(dx))
 10. └─base::.handleSimpleError(...)
 11.   └─dplyr (local) h(simpleError(msg, call))
 12.     └─rlang::abort(...)
Execution halted

Many thanks,
Evan

**Comment by fabou-uobaf** [comment]
Dear Evan 

Thanks for your interest in VaQuERo. 

Most of those errors warnings are due to the fact that I did not update the default values of the command line options to new functionality and changed input files. Sorry for that. I did now and hope it works.

Please pull the newest version and try the following:

git clone https://github.com/fabou-uobaf/VaQuERo.git
Rscript VaQuERo/scripts/VaQuERo.r --debug TRUE 

Hope this helps, if not please do not hesitate to get back.

Fabian

**Comment by EvaFriederike** [comment]
Hi @fabou-uobaf ,

I had the same issues with testing the script. After pulling your fixed version, the file reading errors and warnings were resolved, but the following script error remained:

Error in `mutate()`:
! Problem while computing `sample_date_decimal =
  decimalDate(sample_date, n)`.
Caused by error in `if ((y%%4) == 0) ...`:
! the condition has length > 1
Backtrace:
     ▆
  1. ├─... %>% dplyr::select(-n)
  2. ├─dplyr::select(., -n)
  3. ├─dplyr::mutate(...)
  4. ├─dplyr:::mutate.data.frame(., sample_date_decimal = decimalDate(sample_date, n))
  5. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
  6. │   ├─base::withCallingHandlers(...)
  7. │   └─mask$eval_all_mutate(quo)
  8. ├─global decimalDate(sample_date, n)
  9. │ └─global leapYear(year(dx))
 10. └─base::.handleSimpleError(...)
 11.   └─dplyr (local) h(simpleError(msg, call))
 12.     └─rlang::abort(...)
Execution halted

Cheers,
Eva

**Comment by fabou-uobaf** [comment]
Hello again.

The issue probably arose from different behavior of the dplyr::ungroup function depending on the versioning. We checked and @luenling fixed the issue. please give it a try.

bw, Fabian

**Comment by EvaFriederike** [comment]
Hi :)

The test case now runs for me without any errors, thx for the quick help!

**Comment by LauraVP1994** [comment]
I also get this error

`Error in fread(file = markermutationFile) :
  File 'VaQuERo/resources/mutations_list_grouped_pango_codonPhased_2023-01-02_Eu     rope.csv' does not exist or is non-readable. `

However, when I check it refers to /data/metaData_general.csv which is indeed not available in the data folder?

**Comment by fabou-uobaf** [comment]
Dear Laura

Indeed the code is quite tailored to our data.

concerning your problem running it, please consider to pull the newest version and run vaquero version 2. version 1 is no more maintained. you can do so by invoking:

``Rscript VaQuERo/scripts/VaQuERo_v2.r --debug TRUE``
